import Link from "next/link";
import { getSelectedClientId } from "@/lib/clients";
import { prisma } from "@/lib/prisma";
import { promptAccessWhere } from "@/lib/prompts";
import { formatDate } from "@/lib/format";

export default async function PromptLibraryPage({ searchParams }: { searchParams: Promise<{ search?: string; template_type?: string; scope?: string; status?: string }> }) {
  const filters = await searchParams; const clientId = await getSelectedClientId();
  const templates = await prisma.promptTemplate.findMany({ where: { AND: [promptAccessWhere(clientId), ...(filters.search ? [{ OR: [{ name: { contains: filters.search } }, { slug: { contains: filters.search } }] }] : [])], ...(filters.template_type ? { templateType: filters.template_type } : {}), ...(filters.scope ? { scope: filters.scope } : {}), ...(filters.status ? { status: filters.status } : {}) }, include: { client: { select: { name: true } }, versions: { orderBy: { versionNumber: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" } });
  return <div className="mx-auto max-w-7xl px-8 py-8">
    <div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Prompt Library</h1><p className="mt-1 text-sm text-zinc-600">Database-backed Markdown prompts and approved versions.</p></div><div className="flex gap-2"><Link href="/prompts/import" className="rounded border border-zinc-300 bg-white px-4 py-2 text-sm">Import Markdown</Link><Link href="/prompts/new" className="rounded bg-zinc-900 px-4 py-2 text-sm text-white">Create prompt</Link></div></div>
    <form className="mb-5 grid gap-3 rounded border border-zinc-200 bg-white p-4 md:grid-cols-4"><input name="search" defaultValue={filters.search} placeholder="Search name or slug" className="rounded border border-zinc-300 px-3 py-2 text-sm"/><select name="template_type" defaultValue={filters.template_type ?? ""} className="rounded border border-zinc-300 px-3 py-2 text-sm"><option value="">All templates</option><option value="spoke">Spoke</option><option value="service_detail">Service Detail</option></select><select name="scope" defaultValue={filters.scope ?? ""} className="rounded border border-zinc-300 px-3 py-2 text-sm"><option value="">All scopes</option>{["global","workspace","industry","client"].map((value)=><option key={value}>{value}</option>)}</select><button className="rounded bg-zinc-800 px-3 py-2 text-sm text-white">Filter</button></form>
    <div className="overflow-hidden rounded border border-zinc-200 bg-white"><div className="grid grid-cols-[1.5fr_120px_100px_100px_90px_120px] gap-3 bg-zinc-50 px-4 py-3 text-xs font-semibold uppercase text-zinc-500"><span>Prompt</span><span>Template</span><span>Scope</span><span>Status</span><span>Version</span><span>Updated</span></div>{templates.length ? templates.map((template)=><Link key={template.id} href={`/prompts/${template.id}`} className="grid grid-cols-[1.5fr_120px_100px_100px_90px_120px] gap-3 border-t border-zinc-100 px-4 py-3 text-sm hover:bg-zinc-50"><span className="min-w-0"><b className="block truncate">{template.name}</b><small className="text-zinc-500">{template.client?.name ?? template.industry ?? template.slug}</small></span><span>{template.templateType}</span><span>{template.scope}</span><span>{template.status}</span><span>{template.currentApprovedVersionId ? `v${template.versions.find((v)=>v.id===template.currentApprovedVersionId)?.versionNumber ?? "approved"}` : "None"}</span><span>{formatDate(template.updatedAt)}</span></Link>) : <p className="p-5 text-sm text-zinc-600">No prompts found.</p>}</div>
  </div>;
}
