"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Version = { id: string; versionNumber: number; markdownContent: string; changeSummary: string; status: string; createdAt: string; approvedAt: string | null };
type Template = { id: string; name: string; slug: string; description: string; templateType: string; scope: string; industry: string | null; status: string; currentApprovedVersionId: string | null; versions: Version[] };

export function PromptEditor({ initialTemplate }: { initialTemplate?: Template }) {
  const router = useRouter(); const latest = initialTemplate?.versions[0];
  const [metadata, setMetadata] = useState({ name: initialTemplate?.name ?? "", slug: initialTemplate?.slug ?? "", description: initialTemplate?.description ?? "", templateType: initialTemplate?.templateType ?? "spoke", scope: initialTemplate?.scope ?? "client", industry: initialTemplate?.industry ?? "" });
  const [selectedVersionId, setSelectedVersionId] = useState(latest?.id ?? "");
  const selected = initialTemplate?.versions.find((version) => version.id === selectedVersionId) ?? latest;
  const [markdown, setMarkdown] = useState(selected?.markdownContent ?? "# Prompt title\n\nWrite instructions here.");
  const [summary, setSummary] = useState(selected?.changeSummary ?? ""); const [html, setHtml] = useState(""); const [dirty, setDirty] = useState(false); const [message, setMessage] = useState(""); const [view, setView] = useState<"split"|"editor"|"preview">("split"); const [diff, setDiff] = useState<{type:string;text:string}[]>([]);
  const editable = !selected || selected.status === "draft";
  useEffect(() => { const timer=setTimeout(()=>fetch("/api/prompts/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({markdown})}).then(r=>r.json()).then(data=>setHtml(data.html??"")),150); return()=>clearTimeout(timer); },[markdown]);
  useEffect(() => { const warn=(event:BeforeUnloadEvent)=>{if(dirty)event.preventDefault();}; window.addEventListener("beforeunload",warn); return()=>window.removeEventListener("beforeunload",warn); },[dirty]);
  async function save() { setMessage(""); if(initialTemplate){const metadataResponse=await fetch(`/api/prompts/${initialTemplate.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(metadata)});if(!metadataResponse.ok){const metadataError=await metadataResponse.json();setMessage(metadataError.error??"Metadata save failed");return;}} const endpoint=initialTemplate?`/api/prompts/${initialTemplate.id}/versions`:"/api/prompts"; const body=initialTemplate?{markdownContent:markdown,changeSummary:summary}:{...metadata,markdownContent:markdown,changeSummary:summary}; const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const data=await res.json(); if(!res.ok){setMessage(data.error??"Save failed");return;} setDirty(false); setMessage("Draft saved."); if(!initialTemplate) router.push(`/prompts/${data.template.id}`); else router.refresh(); }
  async function approve(){if(!selected)return;const res=await fetch(`/api/prompts/${initialTemplate!.id}/versions/${selected.id}/approve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({changeSummary:summary})});const data=await res.json();setMessage(res.ok?"Version approved.":data.error);if(res.ok)router.refresh();}
  async function compare(){if(!initialTemplate||!selected||!initialTemplate.currentApprovedVersionId||selected.id===initialTemplate.currentApprovedVersionId)return;const res=await fetch(`/api/prompts/${initialTemplate.id}/diff?from=${initialTemplate.currentApprovedVersionId}&to=${selected.id}`);const data=await res.json();setDiff(data.lines??[]);}
  async function archive(){if(!initialTemplate)return;const res=await fetch(`/api/prompts/${initialTemplate.id}/archive`,{method:"POST"});setMessage(res.ok?"Prompt archived.":"Archive failed.");if(res.ok)router.refresh();}
  async function duplicate(){const res=await fetch("/api/prompts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...metadata,name:`${metadata.name} Copy`,slug:`${metadata.slug}-copy`,markdownContent:markdown,changeSummary:"Duplicated prompt"})});const data=await res.json();if(res.ok)router.push(`/prompts/${data.template.id}`);else setMessage(data.error??"Duplicate failed");}
  async function createDraft(){if(!initialTemplate)return;const res=await fetch(`/api/prompts/${initialTemplate.id}/versions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({markdownContent:markdown,changeSummary:`Draft copied from v${selected?.versionNumber ?? ""}`})});const data=await res.json();setMessage(res.ok?"New draft created.":data.error??"Could not create draft");if(res.ok)router.refresh();}
  const words=useMemo(()=>markdown.trim()?markdown.trim().split(/\s+/).length:0,[markdown]);
  return <div className="space-y-5"><div className="grid gap-3 rounded border border-zinc-200 bg-white p-4 md:grid-cols-3">{Object.entries(metadata).map(([key,value])=><label key={key} className={key==="description"?"md:col-span-2":""}><span className="mb-1 block text-xs font-semibold uppercase text-zinc-500">{key}</span>{key==="scope"?<select value={value} onChange={e=>{setMetadata({...metadata,[key]:e.target.value});setDirty(true);}} className="w-full rounded border border-zinc-300 px-3 py-2 text-sm">{["global","workspace","industry","client"].map(v=><option key={v}>{v}</option>)}</select>:key==="templateType"?<select value={value} onChange={e=>{setMetadata({...metadata,[key]:e.target.value});setDirty(true);}} className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"><option value="spoke">Spoke</option><option value="service_detail">Service Detail</option><option value="custom">Custom</option></select>:<input value={value} onChange={e=>{setMetadata({...metadata,[key]:e.target.value});setDirty(true);}} className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"/>}</label>)}</div>
    {initialTemplate&&<div className="flex flex-wrap items-center gap-3"><select value={selectedVersionId} onChange={e=>{const version=initialTemplate.versions.find(v=>v.id===e.target.value)!;setSelectedVersionId(e.target.value);setMarkdown(version.markdownContent);setSummary(version.changeSummary);setDirty(false);setDiff([]);}} className="rounded border border-zinc-300 px-3 py-2 text-sm">{initialTemplate.versions.map(v=><option key={v.id} value={v.id}>v{v.versionNumber} · {v.status}</option>)}</select><a href={`/api/prompts/${initialTemplate.id}/versions/${selected?.id}/export`} className="rounded border border-zinc-300 px-3 py-2 text-sm">Export Markdown</a><button onClick={compare} className="rounded border border-zinc-300 px-3 py-2 text-sm">Compare to approved</button></div>}
    <div className="flex gap-2">{(["split","editor","preview"] as const).map(mode=><button key={mode} onClick={()=>setView(mode)} className={`rounded px-3 py-1.5 text-sm ${view===mode?"bg-zinc-900 text-white":"border border-zinc-300"}`}>{mode}</button>)}</div>
    <div className={`grid gap-4 ${view === "split" ? "lg:grid-cols-2" : ""}`}>
      {view !== "preview" && <div><textarea value={markdown} readOnly={!editable} onChange={e=>{setMarkdown(e.target.value);setDirty(true);}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();void save();}}} rows={30} className="w-full rounded border border-zinc-300 bg-zinc-950 p-4 font-mono text-sm leading-6 text-zinc-100"/><p className="mt-1 text-xs text-zinc-500">{words} words · {markdown.length} characters · Ctrl/Cmd+S to save</p></div>}
      {view !== "editor" && <div className="article-body min-h-[720px] rounded border border-zinc-200 bg-white p-6" dangerouslySetInnerHTML={{__html:html}}/>}
    </div>
    <label className="block"><span className="mb-1 block text-xs font-semibold uppercase text-zinc-500">Change summary</span><input value={summary} onChange={e=>{setSummary(e.target.value);setDirty(true);}} className="w-full rounded border border-zinc-300 px-3 py-2 text-sm"/></label>
    <div className="flex flex-wrap gap-2"><button onClick={()=>void save()} disabled={!editable} className="rounded bg-zinc-900 px-4 py-2 text-sm text-white disabled:opacity-40">Save draft</button>{selected?.status==="draft"?<button onClick={()=>void approve()} className="rounded bg-emerald-700 px-4 py-2 text-sm text-white">Approve version</button>:initialTemplate&&<button onClick={()=>void createDraft()} className="rounded bg-zinc-700 px-4 py-2 text-sm text-white">Create editable draft</button>}{initialTemplate&&<><button onClick={()=>void duplicate()} className="rounded border border-zinc-300 px-4 py-2 text-sm">Duplicate</button><button onClick={()=>void archive()} className="rounded border border-red-300 px-4 py-2 text-sm text-red-700">Archive</button></>}<span className="py-2 text-sm text-zinc-600">{message}</span></div>
    {diff.length>0&&<div className="rounded border border-zinc-200 bg-white p-4 font-mono text-xs">{diff.map((line,index)=><div key={index} className={line.type==="added"?"bg-emerald-50 text-emerald-800":line.type==="removed"?"bg-red-50 text-red-800":"text-zinc-500"}>{line.type==="added"?"+":line.type==="removed"?"-":" "} {line.text}</div>)}</div>}
  </div>;
}
