"use client";
import { useState } from "react"; import { useRouter } from "next/navigation";
type Revision = { id: string; revisionNumber: number; createdAt: string; source: string; html: string; inputsJson: string; seoJson: string; validationJson: string };
type Props = { page: { id: string; title: string; status: string; wordpressPostId: string | null; wordpressUrl: string | null; currentRevision: { id: string; html: string; inputs: Record<string, unknown>; sections: Array<string | { id: string; label: string }>; seo: { title: string; metaDescription: string; slug: string; primaryKeyword: string; wordpressStatus: string }; validation: { status: string; seoScore: number; accessibilityScore: number; checks: Array<{ id: string; label: string; severity: string; message: string }> } }; revisions: Revision[] } };
function highlightedHtml(value:string){const escaped=value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");return escaped.replace(/(&lt;\/?)([a-z][\w-]*)/gi,'<span class="text-zinc-500">$1</span><span class="text-blue-700">$2</span>').replace(/([\w-]+)(=)(&quot;[^&]*?&quot;|"[^"]*")/g,'<span class="text-violet-700">$1</span>$2<span class="text-emerald-700">$3</span>');}
export function ServicePageEditor({ page }: Props) { const router = useRouter(); const current = page.currentRevision; const [html, setHtml] = useState(current.html); const [seo, setSeo] = useState(current.seo); const [mode, setMode] = useState<"preview" | "html">("preview"); const [width, setWidth] = useState("100%"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const importedLinks = Array.isArray(current.inputs.detectedInternalLinks) ? current.inputs.detectedInternalLinks.length : 0; const importedImages = Array.isArray(current.inputs.detectedImages) ? current.inputs.detectedImages.length : 0;
  async function call(url: string, body?: unknown) { setBusy(true); setMessage(""); const res = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body ?? {}) }); const json = await res.json(); setBusy(false); if (!res.ok) { setMessage(json.code === "WORDPRESS_CHANGED" ? `${json.error} Use “Overwrite WordPress” only after reviewing the remote page.` : json.detail || json.error); return { ok: false, json }; } router.refresh(); return { ok: true, json }; }
  async function save() { const result = await call(`/api/service-pages/${page.id}/revisions`, { html, seo }); if (result.ok) setMessage("Saved as a new revision."); }
  function cancelEdit(){setHtml(current.html);setSeo(current.seo);setMode("preview");setMessage("Edits discarded.");}
  async function publish(force = false, status: "draft" | "publish" = "draft") { if (status === "publish" && !confirm("Publish this page live in WordPress?")) return; const result = await call(`/api/service-pages/${page.id}/publish`, { force, status }); if (result.ok) setMessage(`WordPress page ${result.json.action}.`); }
  return <div className="grid gap-5"><div className="flex flex-wrap items-center gap-2 rounded-lg border border-zinc-200 bg-white p-4"><span className={`rounded px-2 py-1 text-xs font-semibold ${current.validation.status === "fail" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800"}`}>{current.validation.status.toUpperCase()}</span><span className="text-sm">SEO {current.validation.seoScore} · Accessibility {current.validation.accessibilityScore} · {page.status.replaceAll("_", " ")}</span><span className="ml-auto text-sm text-zinc-500">{page.wordpressPostId ? `WordPress #${page.wordpressPostId}` : "Not yet in WordPress"}</span></div>
    <div className="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><aside className="grid content-start gap-4"><div className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold">SEO & publishing</h2><label className="mt-3 grid gap-1 text-xs">SEO title<input value={seo.title} onChange={(e)=>setSeo({...seo,title:e.target.value})} className="rounded border p-2 text-sm"/></label><label className="mt-3 grid gap-1 text-xs">Meta description<textarea value={seo.metaDescription} onChange={(e)=>setSeo({...seo,metaDescription:e.target.value})} className="rounded border p-2 text-sm"/></label><label className="mt-3 grid gap-1 text-xs">Slug<input value={seo.slug} onChange={(e)=>setSeo({...seo,slug:e.target.value})} className="rounded border p-2 text-sm"/></label><label className="mt-3 grid gap-1 text-xs">Primary keyword<input value={seo.primaryKeyword} onChange={(e)=>setSeo({...seo,primaryKeyword:e.target.value})} className="rounded border p-2 text-sm"/></label></div>
    <div className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold">Imported package</h2><dl className="mt-2 grid grid-cols-[110px_1fr] gap-1 text-xs"><dt className="text-zinc-500">Service</dt><dd>{String(current.inputs.serviceName || "Not detected")}</dd><dt className="text-zinc-500">Template</dt><dd>{String(current.inputs.templateVersion || "Not specified")}</dd><dt className="text-zinc-500">Parent</dt><dd>{String(current.inputs.parent || "Not specified")}</dd><dt className="text-zinc-500">Internal links</dt><dd>{importedLinks}</dd><dt className="text-zinc-500">Images</dt><dd>{importedImages}</dd></dl></div>
    <div className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold">Validation</h2><div className="mt-3 grid gap-2">{current.validation.checks.map((check)=><div key={check.id} className="text-xs"><b className={check.severity === "fail" ? "text-red-700" : check.severity === "warning" ? "text-amber-700" : "text-emerald-700"}>{check.severity.toUpperCase()}</b> {check.label}<p className="text-zinc-500">{check.message}</p></div>)}</div></div>
    <div className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold">Detected sections</h2><div className="mt-2 grid gap-1">{current.sections.length ? current.sections.map((section)=><span key={typeof section === "string" ? section : section.id} className="text-xs text-zinc-600">✓ {typeof section === "string" ? section.replaceAll("-", " ") : section.label}</span>) : <span className="text-xs text-amber-700">No semantic sections detected.</span>}</div></div>
    <div className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold">Revision history</h2><div className="mt-2 grid gap-2">{page.revisions.map((r)=><div key={r.id} className="flex items-center justify-between text-xs"><span>v{r.revisionNumber} · {r.source}</span>{r.id !== current.id && <button disabled={busy} onClick={async()=>{ const result=await call(`/api/service-pages/${page.id}/revisions/${r.id}/restore`); if(result.ok) location.reload(); }} className="underline">Restore</button>}</div>)}</div></div></aside>
    <section className="min-w-0 rounded-lg border border-zinc-200 bg-white"><div className="flex flex-wrap gap-2 border-b p-3"><button onClick={()=>setMode("preview")} className="rounded border px-3 py-1 text-sm">Preview</button><button onClick={()=>setMode("html")} className="rounded border px-3 py-1 text-sm">Edit HTML</button>{mode === "preview" && <><button onClick={()=>setWidth("1440px")} className="rounded border px-2 py-1 text-xs">Desktop</button><button onClick={()=>setWidth("768px")} className="rounded border px-2 py-1 text-xs">Tablet</button><button onClick={()=>setWidth("390px")} className="rounded border px-2 py-1 text-xs">Mobile</button></>}{mode === "html"&&<button onClick={cancelEdit} className="ml-auto rounded border px-3 py-1 text-sm">Cancel</button>}<button disabled={busy} onClick={save} className={`${mode==="preview"?"ml-auto":""} rounded bg-zinc-800 px-3 py-1 text-sm text-white`}>Save revision</button></div>{mode === "preview" ? <div className="overflow-auto bg-zinc-100 p-4"><iframe title="Service page preview" sandbox="" srcDoc={html} style={{width}} className="mx-auto min-h-[800px] max-w-full border bg-white"/></div> : <div className="relative min-h-[800px] overflow-hidden bg-white"><pre aria-hidden="true" className="pointer-events-none absolute inset-0 min-h-[800px] whitespace-pre-wrap break-words p-4 font-mono text-xs leading-5" dangerouslySetInnerHTML={{__html:highlightedHtml(html)}}/><textarea aria-label="Page HTML" value={html} onChange={(e)=>setHtml(e.target.value)} spellCheck={false} className="absolute inset-0 min-h-[800px] w-full resize-none bg-transparent p-4 font-mono text-xs leading-5 text-transparent caret-black selection:bg-blue-200"/></div>}</section></div>
    {message && <p className="rounded bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}<div className="flex flex-wrap justify-end gap-2"><button disabled={busy || current.validation.status === "fail"} onClick={()=>publish(false,"draft")} className="rounded bg-zinc-900 px-4 py-2 text-sm text-white disabled:opacity-40">{page.wordpressPostId ? "Update WordPress Page" : "Publish to WordPress as Draft"}</button><button disabled={busy || current.validation.status === "fail"} onClick={()=>publish(false,"publish")} className="rounded bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-40">Publish Live</button>{message.includes("modified in WordPress") && <><button disabled={busy} onClick={async()=>{const result=await call(`/api/service-pages/${page.id}/pull`);if(result.ok)location.reload();}} className="rounded border px-4 py-2 text-sm">Pull WordPress Version</button><button disabled={busy} onClick={()=>publish(true,"draft")} className="rounded bg-red-700 px-4 py-2 text-sm text-white">Overwrite WordPress</button></>}{page.wordpressUrl && <a href={page.wordpressUrl} target="_blank" rel="noreferrer" className="rounded border px-4 py-2 text-sm">Open WordPress</a>}</div></div>; }
