"use client";
import Link from "next/link"; import { useRef, useState } from "react";
type Issue = { row: number; field?: string; severity: string; message: string };
type Result = { pages: Array<{ id: string; title: string; slug: string; status: string }>; counts: { imported: number; ready: number; warnings: number; failed: number }; issues: Issue[] };
export function ServicePageImportForm() { const inputRef = useRef<HTMLInputElement>(null); const [file,setFile]=useState<File|null>(null); const [dragging,setDragging]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [issues,setIssues]=useState<Issue[]>([]); const [result,setResult]=useState<Result|null>(null);
  function accept(candidate?: File) { if (!candidate) return; if (!/\.csv$/i.test(candidate.name)) return setError("Choose a .csv file."); setFile(candidate); setError(""); setIssues([]); setResult(null); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if(!file)return; setBusy(true);setError("");setIssues([]);const form=new FormData();form.set("file",file);const res=await fetch("/api/service-pages/import",{method:"POST",body:form});const json=await res.json();setBusy(false);if(!res.ok){setError(json.error||"Import failed.");setIssues(json.issues||[]);return;}setResult(json); }
  if(result) return <div className="grid gap-5 rounded-xl border bg-white p-6"><div><h2 className="text-xl font-semibold">{result.counts.imported} pages imported</h2><p className="mt-1 text-sm text-zinc-600">{result.counts.ready} Ready for Review · {result.counts.warnings} Validation Warning · {result.counts.failed} Validation Failed</p></div><div className="divide-y rounded border">{result.pages.map((page)=><Link key={page.id} href={`/service-pages/${page.id}`} className="flex items-center justify-between p-3 text-sm hover:bg-zinc-50"><span><b>{page.title}</b><small className="block text-zinc-500">/{page.slug}/</small></span><span className="capitalize">{page.status.replaceAll("_"," ")}</span></Link>)}</div><Link href="/service-pages" className="rounded bg-zinc-900 px-4 py-2 text-center text-sm text-white">View all service pages</Link></div>;
  return <form onSubmit={submit} className="grid gap-5 rounded-xl border bg-white p-6"><button type="button" onClick={()=>inputRef.current?.click()} onDragOver={(e)=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={(e)=>{e.preventDefault();setDragging(false);accept(e.dataTransfer.files[0])}} className={`grid min-h-52 place-items-center rounded-xl border-2 border-dashed p-8 text-center ${dragging?"border-zinc-900 bg-zinc-50":"border-zinc-300"}`}><span><b className="block text-lg">{file?file.name:"Drop service-page CSV here"}</b><span className="mt-2 block text-sm text-zinc-500">{file?`${Math.ceil(file.size/1024)} KB · click to replace`:"or click to browse"}</span></span></button><input ref={inputRef} type="file" accept=".csv,text/csv" className="hidden" onChange={(e)=>accept(e.target.files?.[0])}/><p className="text-sm text-zinc-500">One client per CSV. Every row becomes an Outpost review draft; nothing is automatically published.</p>{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{issues.length>0&&<div className="max-h-64 overflow-auto rounded border border-red-200 bg-red-50 p-3">{issues.map((issue,index)=><p key={`${issue.row}-${issue.field}-${index}`} className="text-xs text-red-800">{issue.row?`Row ${issue.row}: `:""}{issue.message}</p>)}</div>}<button disabled={busy||!file} className="rounded bg-zinc-900 px-5 py-3 font-medium text-white disabled:opacity-40">{busy?"Validating & importing…":"Import pages"}</button></form>; }
