"use client";
import { useState } from "react";
type ProfileState = { businessName?: string; domain?: string; wordpressRestBase?: string; brand?: Record<string, string>; template?: Record<string, string | boolean>; internalLinks?: Array<{ title?: string; anchor: string; url: string; targetPageId?: number; content_type?: string; service_hub?: string }>; [key: string]: unknown };
export function SiteProfileForm({ initial }: { initial: ProfileState }) {
  const [profile,setProfile]=useState(initial);const [message,setMessage]=useState("");const brand=profile.brand??{};const template=profile.template??{};
  const setTemplate=(key:string,value:string|boolean)=>setProfile({...profile,template:{...template,[key]:value}});
  async function save(e:React.FormEvent){e.preventDefault();const res=await fetch("/api/site-profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});const json=await res.json();setMessage(res.ok?"Site profile saved.":json.error);}
  return <form onSubmit={save} className="grid gap-5 rounded-lg border bg-white p-6"><div className="grid gap-4 md:grid-cols-2">{[["Business name","businessName"],["Domain / canonical site URL","domain"],["WordPress REST base","wordpressRestBase"]].map(([label,key])=><label key={key} className="grid gap-1 text-sm">{label}<input value={String(profile[key]??"")} onChange={(e)=>setProfile({...profile,[key]:e.target.value})} className="rounded border p-2"/></label>)}{[["Primary color","primary"],["Accent color","accent"],["Text color","text"],["Background color","background"],["Heading font","headingFont"],["Body font","bodyFont"],["Border radius","radius"],["Container width","container"],["Section spacing","spacing"]].map(([label,key])=><label key={key} className="grid gap-1 text-sm">{label}<input value={brand[key]??""} onChange={(e)=>setProfile({...profile,brand:{...brand,[key]:e.target.value}})} className="rounded border p-2"/></label>)}</div>
  <section className="rounded border p-4"><h2 className="mb-3 font-semibold">Service Detail technical SEO</h2><div className="grid gap-4 md:grid-cols-2">{[["Verified provider @id","schemaEntityId","https://example.com/#organization"],["Schema entity type","schemaType","Organization"],["Provider URL","providerUrl","https://example.com/"],["Provider telephone","providerTelephone","+1 555 555 5555"],["Provider email","providerEmail","hello@example.com"],["Street address","providerStreetAddress","123 Main St"],["Address locality","providerAddressLocality","City"],["Address region","providerAddressRegion","PA"],["Postal code","providerPostalCode","12345"],["Address country","providerAddressCountry","US"],["Home breadcrumb label","defaultHomeLabel","Home"],["Global stylesheet URL","globalStylesheetUrl","https://example.com/.../service-detail.css"],["Default CTA text","defaultCtaText","Contact us"],["Default CTA URL","defaultCtaUrl","/contact/"]].map(([label,key,placeholder])=><label key={key} className="grid gap-1 text-sm">{label}<input value={String(template[key]??"")} placeholder={placeholder} onChange={(e)=>setTemplate(key,e.target.value)} className="rounded border p-2"/></label>)}</div><label className="mt-4 grid gap-1 text-sm"><span>Service areas for schema</span><textarea rows={3} value={String(template.serviceAreas??"")} placeholder="Bucks County, Pennsylvania|Montgomery County, Pennsylvania" onChange={(e)=>setTemplate("serviceAreas",e.target.value)} className="rounded border p-3 text-sm"/><span className="text-xs text-zinc-500">Separate multiple areas with a pipe or a new line.</span></label><label className="mt-4 grid gap-1 text-sm"><span>Global service-detail CSS</span><textarea rows={16} value={String(template.globalStylesheetCss??"")} placeholder="Paste the same .outpost-service-page CSS used in WordPress Additional CSS." onChange={(e)=>setTemplate("globalStylesheetCss",e.target.value)} className="rounded border p-3 font-mono text-xs"/><span className="text-xs text-zinc-500">Injected directly into Outpost previews. Keep article HTML free of style elements. If a stylesheet URL is also set, this pasted CSS loads after it.</span></label><div className="mt-4 grid gap-2 md:grid-cols-2">{[["Require hero image","requireServiceHeroImage",true],["Require supporting image","requireServiceSupportingImage",false],["Enable Service schema","enableServiceSchema",true],["Enable FAQ schema","enableFaqSchema",true],["Enable breadcrumb schema","enableBreadcrumbSchema",true],["Set hero as featured image","setHeroAsFeaturedImage",true]].map(([label,key,fallback])=><label key={String(key)} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={typeof template[String(key)]==="boolean"?Boolean(template[String(key)]):Boolean(fallback)} onChange={(e)=>setTemplate(String(key),e.target.checked)}/>{String(label)}</label>)}</div></section>
  <label className="grid gap-1 text-sm">Existing site inventory / internal links (JSON array)<textarea rows={6} value={JSON.stringify(profile.internalLinks??[],null,2)} onChange={(e)=>{try{setProfile({...profile,internalLinks:JSON.parse(e.target.value) as ProfileState["internalLinks"]})}catch{}}} className="rounded border p-2 font-mono text-xs"/></label>{message&&<p className="text-sm text-blue-700">{message}</p>}<button className="rounded bg-zinc-900 px-4 py-2 text-white">Save site profile</button></form>;
}
