import type { ServiceDetailPayload } from "@/lib/templates";
import type { ServiceDetailRenderResult, ServiceDetailSeoConfig } from "@/lib/service-detail-render";
export type TechnicalSeoItem = { id: string; message: string };
export type TechnicalSeoValidation = { errors: TechnicalSeoItem[]; warnings: TechnicalSeoItem[]; passes: TechnicalSeoItem[] };
const strip = (value = "") => value.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
const urlValid = (value = "", allowRelative = true) => { if (allowRelative && value.startsWith("/")) return true; try { return new URL(value).protocol === "https:"; } catch { return false; } };
const ctaUrlValid = (value = "") => urlValid(value) || /^tel:\+?[0-9() .-]+$/i.test(value);
export function validateServiceDetailForPublish(record: ServiceDetailPayload, rendered: ServiceDetailRenderResult, config: ServiceDetailSeoConfig = {}): TechnicalSeoValidation {
  const errors: TechnicalSeoItem[] = [], warnings: TechnicalSeoItem[] = [], passes: TechnicalSeoItem[] = [];
  const check = (id: string, ok: boolean, message: string, severity: "error" | "warning" = "error") => (ok ? passes : severity === "error" ? errors : warnings).push({ id, message });
  check("post-title", Boolean(record.post_title?.trim()), "Post title is present."); check("slug", Boolean(record.post_name?.trim()), "Slug is present."); check("meta-title", Boolean(record.meta_title?.trim()), "Meta title is present."); check("meta-description", Boolean(record.meta_description?.trim()), "Meta description is present.");
  check("meta-title-length", record.meta_title.length <= 60, `Meta title is ${record.meta_title.length} characters.`, "warning"); check("meta-description-length", record.meta_description.length <= 160, `Meta description is ${record.meta_description.length} characters.`, "warning");
  check("canonical", Boolean(rendered.seo.canonicalUrl && urlValid(rendered.seo.canonicalUrl, false)), "Canonical URL is resolvable."); check("robots", !record.robots || /^(index|noindex)(,(follow|nofollow))?$/i.test(record.robots), "Robots value is valid.");
  const h1s = rendered.bodyHtml.match(/<h1\b/gi)?.length ?? 0; check("one-h1", h1s === 1, `Exactly one H1 is required; found ${h1s}.`); check("empty-headings", !/<h[1-6]\b[^>]*>\s*<\/h[1-6]>/i.test(rendered.bodyHtml), "No empty headings found.", "warning");
  check("no-style", !/<style\b/i.test(rendered.bodyHtml), "Published body contains no inline stylesheet."); check("no-script", !/<script\b/i.test(rendered.bodyHtml), "Published body contains no scripts."); check("no-js-url", !/(?:href|src)=["']\s*(?:javascript:|data:)/i.test(rendered.bodyHtml), "No unsafe URL schemes found."); check("no-events", !/\son\w+\s*=/i.test(rendered.bodyHtml), "No inline event handlers found.");
  const ids = [...rendered.bodyHtml.matchAll(/\sid=["']([^"']+)["']/gi)].map((match) => match[1]); check("unique-ids", ids.length === new Set(ids).size, "HTML IDs are unique."); check("mojibake", !/(?:Ã¢Å“|Ã¢â‚¬â€œ|Ã¢â‚¬â€|Ã¢â€ |ï¿½|â€™|â€œ|â€)/i.test(record.html_content || ""), "No mojibake patterns found.");
  if (/(?:\u00c3.|\u00e2.|\ufffd)/i.test(record.html_content || "") && !errors.some((item) => item.id === "mojibake")) errors.push({ id: "mojibake", message: "Possible broken character encoding detected." });
  const requireHero = config.requireServiceHeroImage !== false; check("hero-image", Boolean(rendered.heroImage?.url) || !requireHero, requireHero ? "Hero image is present." : "Hero image is optional.", requireHero ? "error" : "warning"); if (rendered.heroImage?.url) { check("hero-url", urlValid(rendered.heroImage.url, false), "Hero URL is safe HTTPS."); check("hero-alt", Boolean(rendered.heroImage.alt.trim()), "Hero image has alt text."); }
  const requireSupporting = config.requireServiceSupportingImage === true; check("supporting-image", Boolean(rendered.supportingImage?.url) || !requireSupporting, rendered.supportingImage ? "Supporting image is present." : "Supporting image is missing.", requireSupporting ? "error" : "warning"); if (rendered.supportingImage?.url) { check("supporting-url", urlValid(rendered.supportingImage.url, false), "Supporting URL is safe HTTPS."); check("supporting-alt", Boolean(rendered.supportingImage.alt.trim()), "Supporting image has alt text."); }
  check("breadcrumb-visible", /class=["'][^"']*sr-breadcrumbs/i.test(rendered.bodyHtml), "Visible breadcrumbs are generated."); const breadcrumbSchema = (rendered.schemaGraph?.["@graph"] as Array<Record<string, unknown>> | undefined)?.find((item) => item["@type"] === "BreadcrumbList"); check("breadcrumb-schema", config.enableBreadcrumbSchema === false || Boolean(breadcrumbSchema), "BreadcrumbList schema is generated."); if (breadcrumbSchema) check("breadcrumb-parity", (breadcrumbSchema.itemListElement as unknown[]).length === rendered.breadcrumbs.length, "Breadcrumb schema matches the visible trail.");
  check("breadcrumb-microdata", config.enableBreadcrumbSchema === false || /itemtype=["']https:\/\/schema\.org\/BreadcrumbList["']/i.test(rendered.bodyHtml), "BreadcrumbList microdata is attached to the visible trail.");
  const serviceSchema = (rendered.schemaGraph?.["@graph"] as Array<Record<string, unknown>> | undefined)?.find((item) => item["@type"] === "Service"); check("service-schema", config.enableServiceSchema === false || !config.schemaEntityId || Boolean(serviceSchema), config.schemaEntityId ? "Service schema is generated." : "Service schema is withheld until a verified provider entity ID is configured.", config.schemaEntityId ? "error" : "warning"); check("provider", config.enableServiceSchema === false || Boolean(config.schemaEntityId), "A verified provider entity ID is configured.", "warning");
  check("provider-details", config.enableServiceSchema === false || !config.schemaEntityId || Boolean(config.businessName && config.providerUrl), "The provider entity includes a verified name and URL.", "warning");
  check("service-microdata", config.enableServiceSchema === false || !config.schemaEntityId || /itemtype=["']https:\/\/schema\.org\/Service["']/i.test(rendered.bodyHtml), "Service microdata references the verified provider entity.");
  check("global-styles", Boolean(config.globalStylesheetUrl || config.globalStylesheetCss?.trim()), "A site-wide service-detail stylesheet is configured.", "warning");
  const faqSchema = (rendered.schemaGraph?.["@graph"] as Array<Record<string, unknown>> | undefined)?.find((item) => item["@type"] === "FAQPage"); check("faq-parity", !rendered.faqs.length || config.enableFaqSchema === false || Boolean(faqSchema && (faqSchema.mainEntity as unknown[]).length === rendered.faqs.length), "FAQ schema matches visible FAQs.");
  const faqQuestions = rendered.bodyHtml.match(/itemtype=["']https:\/\/schema\.org\/Question["']/gi)?.length ?? 0; check("faq-microdata", !rendered.faqs.length || config.enableFaqSchema === false || faqQuestions === rendered.faqs.length, "FAQ microdata matches every visible FAQ.");
  const links = [...rendered.bodyHtml.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)]; check("internal-links", links.some((match) => match[1].startsWith("/")), "At least one contextual internal link is present.", "warning"); for (const match of links) { const anchor = strip(match[2]); if (/^(continue reading|click here|learn more)$/i.test(anchor)) warnings.push({ id: "generic-anchor", message: `Generic link anchor found: “${anchor}”.` }); if (/^https?:/i.test(match[1])) check("external-https", match[1].startsWith("https://"), `External URL uses HTTPS: ${match[1]}`); }
  if (record.cta_url) check("cta-url", ctaUrlValid(record.cta_url), "CTA URL must be a relative path, HTTPS URL, or telephone link.");
  try { JSON.stringify(rendered.schemaGraph); passes.push({ id: "schema-json", message: "Schema graph serializes successfully." }); } catch { errors.push({ id: "schema-json", message: "Schema graph could not be serialized." }); }
  return { errors, warnings, passes };
}
